// import React from 'react';

// const reset = () => {
//     return (
//         <div>

// "files.autoSave": "onFocusChange",
//   "tailwindCSS.emmetCompletions": true,
//   "emmet.includeLanguages": {
//     "javascript": "javascriptreact"
//   },
//   "workbench.colorTheme": "Night Owl",
//   "workbench.iconTheme": "material-icon-theme",
//   "editor.fontFamily": "operator mono",
//   "editor.mouseWheelZoom": true,
//   "liveServer.settings.donotShowInfoMsg": true,
//   "workbench.editor.enablePreview": false,
//   "git.openRepositoryInParentFolders": "never",
//   "workbench.statusBar.visible": false,
//   "window.commandCenter": true,
//   "breadcrumbs.enabled": false,
//   "editor.renderWhitespace": "all",
//   "editor.minimap.enabled": false,
//   "window.zoomLevel": 2,
//   "code-runner.executorMapByFileExtension": {
//     ".vb": "cd $dir && vbc /nologo $fileName && $dir$fileNameWithoutExt",
//     ".vbs": "cscript //Nologo",
//     ".scala": "scala",
//     ".jl": "julia",
//     ".cr": "crystal",
//     ".ml": "ocaml",
//     ".zig": "zig run",
//     ".exs": "elixir",
//     ".hx": "haxe --cwd $dirWithoutTrailingSlash --run $fileNameWithoutExt",
//     ".rkt": "racket",
//     ".scm": "csi -script",
//     ".ahk": "autohotkey",
//     ".au3": "autoit3",
//     ".kt": "cd $dir && kotlinc $fileName -include-runtime -d $fileNameWithoutExt.jar && java -jar $fileNameWithoutExt.jar",
//     ".kts": "kotlinc -script",
//     ".dart": "dart",
//     ".pas": "cd $dir && fpc $fileName && $dir$fileNameWithoutExt",
//     ".pp": "cd $dir && fpc $fileName && $dir$fileNameWithoutExt",
//     ".d": "cd $dir && dmd $fileName && $dir$fileNameWithoutExt",
//     ".hs": "runhaskell",
//     ".nim": "nim compile --verbosity:0 --hints:off --run",
//     ".csproj": "dotnet run --project",
//     ".fsproj": "dotnet run --project",
//     ".lisp": "sbcl --script",
//     ".kit": "kitc --run",
//     ".v": "v run",
//     ".vsh": "v run",
//     ".sass": "sass --style expanded",
//     ".cu": "cd $dir && nvcc $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
//     ".ring": "ring",
//     ".sml": "cd $dir && sml $fileName"
//   },
//   "code-runner.executorMap": {
//     "javascript": "node",
//     "java": "cd $dir && javac $fileName && java $fileNameWithoutExt",
//     "c": "cd $dir && gcc $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
//     "zig": "zig run",
//     "cpp": "cd $dir && g++ $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
//     "objective-c": "cd $dir && gcc -framework Cocoa $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
//     "php": "php",
//     "python": "python -u",
//     "perl": "perl",
//     "perl6": "perl6",
//     "ruby": "ruby",
//     "go": "go run",
//     "lua": "lua",
//     "groovy": "groovy",
//     "powershell": "powershell -ExecutionPolicy ByPass -File",
//     "bat": "cmd /c",
//     "shellscript": "bash",
//     "fsharp": "fsi",
//     "csharp": "scriptcs",
//     "vbscript": "cscript //Nologo",
//     "typescript": "ts-node",
//     "coffeescript": "coffee",
//     "scala": "scala",
//     "swift": "swift",
//     "julia": "julia",
//     "crystal": "crystal",
//     "ocaml": "ocaml",
//     "r": "Rscript",
//     "applescript": "osascript",
//     "clojure": "lein exec",
//     "haxe": "haxe --cwd $dirWithoutTrailingSlash --run $fileNameWithoutExt",
//     "rust": "cd $dir && rustc $fileName && $dir$fileNameWithoutExt",
//     "racket": "racket",
//     "scheme": "csi -script",
//     "ahk": "autohotkey",
//     "autoit": "autoit3",
//     "dart": "dart",
//     "pascal": "cd $dir && fpc $fileName && $dir$fileNameWithoutExt",
//     "d": "cd $dir && dmd $fileName && $dir$fileNameWithoutExt",
//     "haskell": "runghc",
//     "nim": "nim compile --verbosity:0 --hints:off --run",
//     "lisp": "sbcl --script",
//     "kit": "kitc --run",
//     "v": "v run",
//     "sass": "sass --style expanded",
//     "scss": "scss --style expanded",
//     "less": "cd $dir && lessc $fileName $fileNameWithoutExt.css",
//     "FortranFreeForm": "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
//     "fortran-modern": "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
//     "fortran_fixed-form": "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
//     "fortran": "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
//     "sml": "cd $dir && sml $fileName"
//   },
            
//   "code-runner.executorMap": {
//     "javascript": "node",
//     "java": "cd $dir && javac $fileName && java $fileNameWithoutExt",
//     "c": "cd $dir && gcc $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
//     "zig": "zig run",
//     "cpp": "cd $dir && g++ $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
//     "objective-c": "cd $dir && gcc -framework Cocoa $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
//     "php": "php",
//     "python": "python -u",
//     "perl": "perl",
//     "perl6": "perl6",
//     "ruby": "ruby",
//     "go": "go run",
//     "lua": "lua",
//     "groovy": "groovy",
//     "powershell": "powershell -ExecutionPolicy ByPass -File",
//     "bat": "cmd /c",
//     "shellscript": "bash",
//     "fsharp": "fsi",
//     "csharp": "scriptcs",
//     "vbscript": "cscript //Nologo",
//     "typescript": "ts-node",
//     "coffeescript": "coffee",
//     "scala": "scala",
//     "swift": "swift",
//     "julia": "julia",
//     "crystal": "crystal",
//     "ocaml": "ocaml",
//     "r": "Rscript",
//     "applescript": "osascript",
//     "clojure": "lein exec",
//     "haxe": "haxe --cwd $dirWithoutTrailingSlash --run $fileNameWithoutExt",
//     "rust": "cd $dir && rustc $fileName && $dir$fileNameWithoutExt",
//     "racket": "racket",
//     "scheme": "csi -script",
//     "ahk": "autohotkey",
//     "autoit": "autoit3",
//     "dart": "dart",
//     "pascal": "cd $dir && fpc $fileName && $dir$fileNameWithoutExt",
//     "d": "cd $dir && dmd $fileName && $dir$fileNameWithoutExt",
//     "haskell": "runghc",
//     "nim": "nim compile --verbosity:0 --hints:off --run",
//     "lisp": "sbcl --script",
//     "kit": "kitc --run",
//     "v": "v run",
//     "sass": "sass --style expanded",
//     "scss": "scss --style expanded",
//     "less": "cd $dir && lessc $fileName $fileNameWithoutExt.css",
//     "FortranFreeForm": "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
//     "fortran-modern": "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
//     "fortran_fixed-form": "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
//     "fortran": "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
//     "sml": "cd $dir && sml $fileName"
//   },
//   "code-runner.clearPreviousOutput": true,
//   "code-runner.saveFileBeforeRun": true,
//   "liveServer.settings.root": "",
//   "code-runner.executorMap": {
//     "php": "c:\\php\\php.exe"
//   },
//   "editor.defaultFormatter": "esbenp.prettier-vscode",
//   "editor.formatOnSave": true,
//   "editor.codeActionsOnSave": {
//     "source.fixAll.eslint": "explicit",
//     "source.fixAll.tslint": "explicit",
//     "source.organizeImports": "explicit"
//   },
//   "eslint.run": "onSave",
//   "emmet.includeLanguages": {
//     "javascript": "javascriptreact"
//   },
//   "path-autocomplete.extensionOnImport": true,
//   "path-autocomplete.excludedItems": {
//     "*/.js": {
//       "when": "**"
//     },
//     "*/.jsx": {
//       "when": "**"
//     }
//   },
//   "javascript.validate.enable": false,
//   "typescript.validate.enable": false
//         </div>
//     );
// };

// export default reset;